# Praktikum 2 - Pra Pengolahan Data (Data Terstruktur: Data Imputation)

**Nama:** Mohammad Al Hafis Hidayatulloh  
**NIM:** 254107023005  
**Mata Kuliah:** RTI235004 - Pembelajaran Mesin  
**Dosen Pengampu:** Usman Nurhasan, S.Kom., M.T.

---

Pada praktikum kedua ini saya melakukan penanganan nilai yang hilang (*data imputation*) pada dataset Titanic, khususnya pada kolom `Age`, `Cabin`, dan `Embarked` yang pada Praktikum 1 terdeteksi memiliki nilai `NaN`.

### Langkah 0 - Persiapan

Mengimpor library `pandas` dan `numpy`.

In [1]:
import pandas as pd
import numpy as np

### Langkah 1 - Memuat Data

Membaca dataset `Titanic-Dataset.csv` dan menampilkan 5 data teratas.

In [2]:
df = pd.read_csv('Titanic-Dataset.csv')
# Tampilkan 5 data teratas
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

### Langkah 2 - Inspeksi Data

Mengecek informasi kolom dan jumlah data yang hilang sebelum dilakukan proses imputasi.

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Langkah 3 - Data Imputation

Mengisi nilai kosong dengan strategi berikut:
- `Age` diisi menggunakan nilai rata-rata (*mean*) yaitu sekitar `29.699118`.
- `Cabin` diisi dengan string `"DECK"` dengan asumsi penumpang tanpa nomor kabin berada di dek kapal.
- `Embarked` diisi menggunakan nilai modus (*mode*) yaitu `'S'` (Southampton).

*Catatan: Pada Pandas versi terbaru (Copy-on-Write), penugasan `df['col'] = df['col'].fillna(...)` digunakan supaya hasil pengisian langsung tersimpan pada DataFrame utama.*

In [5]:
# Age - mean
df['Age'] = df['Age'].fillna(value=df['Age'].mean())

# Cabin - "DECK"
df['Cabin'] = df['Cabin'].fillna(value="DECK")

# Embarked - modus
df['Embarked'] = df['Embarked'].fillna(value=df['Embarked'].mode()[0])

### Langkah 4 - Validasi Hasil

Mengecek kembali dengan `df.info()`, `df.isnull().sum()`, dan menampilkan 10 baris pertama untuk memastikan seluruh nilai `NaN` sudah terisi.

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    str
 11  Embarked     891 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [7]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [8]:
df.head(10)

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500  DECK         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250  DECK         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500  DECK         S
5            6         0       3  ...   8.4583  DECK         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750  DECK         S
8            9         1       3  ...  11.1333  DECK         S
9           10         1       2  ...  30.0708  DECK         C

[10 rows x 12 columns]

Dari hasil validasi `df.info()` dan `df.isnull().sum()`, seluruh 12 kolom sekarang sudah memiliki 891 data *non-null* (tidak ada lagi data yang bernilai `NaN`). Pada tabel `df.head(10)` juga terlihat jelas bahwa penumpang pada indeks ke-5 (`Moran, Mr. James`) yang tadinya memiliki nilai `Age` kosong kini sudah terisi dengan nilai rata-rata `29.699118`, dan penumpang yang tadinya tidak memiliki data kabin (seperti indeks 0, 2, 4, 5, 7, 8, 9) kini kolom `Cabin`-nya sudah berubah menjadi `DECK`.