# Praktikum 3 - Seleksi Fitur, Encoding, dan Standardisasi

**Nama:** Mohammad Al Hafis Hidayatulloh  
**NIM:** 254107023005  
**Mata Kuliah:** RTI235004 - Pembelajaran Mesin  
**Dosen Pengampu:** Usman Nurhasan, S.Kom., M.T.

---

Pada praktikum ketiga ini saya menggunakan file `Titanic-Dataset-fixed.csv` (data Titanic hasil imputasi) untuk melakukan pemilihan fitur (*feature selection* sederhana), mengubah variabel kategorikal menjadi numerik dengan `LabelEncoder`, dan melakukan standardisasi pada kolom `Age` dengan `StandardScaler`.

### Langkah 0 & 1 - Load Data

Mengimpor library yang dibutuhkan (`pandas`, `LabelEncoder`, `StandardScaler`) dan memuat data `Titanic-Dataset-fixed.csv`.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

dpath = 'Titanic-Dataset-fixed.csv'
df = pd.read_csv(dpath)
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500  DECK         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250  DECK         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500  DECK         S

[5 rows x 12 columns]

### Langkah 2 - Slice Data

Memilih variabel yang digunakan sebagai fitur yaitu `Survived`, `Pclass`, `Age`, `Sex`, dan `Cabin`.

In [2]:
df = df[['Survived', 'Pclass', 'Age', 'Sex', 'Cabin']]
df.head()

   Survived  Pclass   Age     Sex Cabin
0         0       3  22.0    male  DECK
1         1       1  38.0  female   C85
2         1       3  26.0  female  DECK
3         1       1  35.0  female  C123
4         0       3  35.0    male  DECK

### Langkah 3 - Encoding

Melakukan *Label Encoding* pada kolom kategorikal `Sex` dan `Cabin` agar nilainya berubah menjadi representasi angka bulat (integer).

In [3]:
le = LabelEncoder() # membuat objek dari LabelEncoder
df['Sex'] = le.fit_transform(df['Sex']) # proses encoding
df['Cabin'] = le.fit_transform(df['Cabin']) # proses encoding

### Langkah 4 - Verifikasi Hasil Encoding

Mengecek kembali 5 data teratas setelah proses encoding.

In [4]:
df.head()

   Survived  Pclass   Age  Sex  Cabin
0         0       3  22.0    1    115
1         1       1  38.0    0     81
2         1       3  26.0    0    115
3         1       1  35.0    0     55
4         0       3  35.0    1    115

Dari hasil encoding di atas, kolom `Sex` yang tadinya berisi string `'male'` dan `'female'` sudah berubah menjadi angka `1` (`male`) dan `0` (`female`). Begitu juga dengan kolom `Cabin`, nilai `'DECK'` dikodekan menjadi `115`, `'C85'` menjadi `81`, `'C123'` menjadi `55`, dan seterusnya sesuai urutan kategori uniknya.

### Langkah 5 - Standarisasi

Melakukan standardisasi pada kolom `Age` menggunakan `StandardScaler` sehingga distribusinya memiliki rata-rata ($\mu$) mendekati 0 dan simpangan baku ($\sigma$) mendekati 1.

In [5]:
std = StandardScaler()
df['Age'] = std.fit_transform(df[['Age']])

### Langkah 6 - Verifikasi Hasil Standarisasi

Mengecek kembali 5 data teratas setelah proses standardisasi.

In [6]:
df.head()

   Survived  Pclass       Age  Sex  Cabin
0         0       3 -0.592481    1    115
1         1       1  0.638789    0     81
2         1       3 -0.284663    0    115
3         1       1  0.407926    0     55
4         0       3  0.407926    1    115

Setelah dilakukan standardisasi dengan `StandardScaler`, nilai pada kolom `Age` kini berada di sekitar angka 0 (ada yang bernilai negatif untuk penumpang yang usianya di bawah rata-rata 29.70 tahun seperti umur 22 tahun yang menjadi `-0.592481` dan umur 26 tahun menjadi `-0.284663`, serta bernilai positif untuk penumpang di atas rata-rata seperti umur 38 tahun menjadi `0.638789` dan umur 35 tahun menjadi `0.407926`).