# Praktikum 2 - Pra Pengolahan Data dan Seleksi Fitur

**Nama:** Mohammad Al Hafis Hidayatulloh  
**NIM:** 254107023005  
**Mata Kuliah:** RTI235004 - Pembelajaran Mesin  
**Dosen Pengampu:** Usman Nurhasan, S.Kom., M.T.

---

Pada praktikum kedua di Jobsheet 3 ini saya melakukan pra pengolahan data terlebih dahulu sebelum melakukan seleksi fitur pada dataset `Titanic-Dataset-fixed.csv`. Tahapan pra pengolahan meliputi encoding pada fitur `Sex` (mapping `'male'` menjadi `1` dan `'female'` menjadi `0`), penyederhanaan fitur `Cabin` menjadi huruf pertama kode dek, demonstrasi imputasi median pada `Age`, serta standardisasi pada `Age` menggunakan `StandardScaler`, kemudian diakhiri dengan pemilihan 5 fitur utama (`Survived`, `Pclass`, `Age`, `Sex`, `Cabin`).

### Langkah 0 - Load Library

Mengimpor library `pandas`, `LabelEncoder`, dan `StandardScaler`.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

### Langkah 1 - Load Data

Memuat dataset `Titanic-Dataset-fixed.csv` dan menampilkan 5 data teratas.

In [2]:
dpath = 'Titanic-Dataset-fixed.csv'
df = pd.read_csv(dpath)
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500  DECK         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250  DECK         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500  DECK         S

[5 rows x 12 columns]

### Langkah 2 & 3 - Pre Processing Encoding `Sex` dan Verifikasi

Melakukan pemetaan (*mapping*) nilai kategorikal pada kolom `Sex` menjadi numerik biner (`'male': 1`, `'female': 0`).

In [3]:
# --- 2. Encoding fitur 'Sex' ---
df['Sex'] = df['Sex'].map({'male': 1, 'female': 0})
print("=== Hasil Setelah Encoding 'Sex' ===")
print(df[['Sex']].head(), "\n")

=== Hasil Setelah Encoding 'Sex' ===
   Sex
0    1
1    0
2    0
3    0
4    1

### Langkah 4 & 5 - Pre Processing Encoding `Cabin` dan Verifikasi

Mengisi nilai kosong (jika ada) pada `Cabin` dengan `'Unknown'`, kemudian mengekstrak karakter pertama dari string `Cabin` untuk merepresentasikan kode dek kapal.

In [4]:
# --- 3. Encoding fitur 'Cabin' ---
df['Cabin'] = df['Cabin'].fillna('Unknown')
print("=== Hasil Setelah Fill NaN pada 'Cabin' ===")
print(df[['Cabin']].head(5), "\n")
df['Cabin'] = df['Cabin'].apply(lambda x: x[0] if x != 'Unknown' else 'U')
print("=== Hasil Ambil huruf pertama 'Cabin' (Deck) ===")
print(df[['Cabin']].head(5), "\n")

=== Hasil Setelah Fill NaN pada 'Cabin' ===
  Cabin
0  DECK
1   C85
2  DECK
3  C123
4  DECK

=== Hasil Ambil huruf pertama 'Cabin' (Deck) ===
  Cabin
0     D
1     C
2     D
3     C
4     D

### Langkah 5 & 6 - Pre Processing Imputasi Data `Age` dan Verifikasi

Mendemonstrasikan proses imputasi nilai kosong pada kolom `Age` menggunakan nilai tengah (*median*).

In [5]:
# --- 4. Imputasi fitur 'Age' dengan median ---
df['Age'] = df[['Age']].fillna(df['Age'].median())
print("=== Hasil Setelah Imputasi Data pada Usia dengan median ===")
print(df[['Age']].head(10), "\n")

=== Hasil Setelah Imputasi Data pada Usia dengan median ===
         Age
0  22.000000
1  38.000000
2  26.000000
3  35.000000
4  35.000000
5  29.699118
6  54.000000
7   2.000000
8  27.000000
9  14.000000

### Langkah 7 & 6 - Pre Processing Standarisasi `Age` dan Verifikasi

Melakukan standardisasi nilai pada kolom `Age` menggunakan `StandardScaler`.

In [6]:
scaler = StandardScaler()
df['Age'] = scaler.fit_transform(df[['Age']])
print("=== Hasil Setelah Standardisasi 'Age' ===")
print(df[['Age']].head(10), "\n")

=== Hasil Setelah Standardisasi 'Age' ===
        Age
0 -0.592481
1  0.638789
2 -0.284663
3  0.407926
4  0.407926
5  0.000000
6  1.870059
7 -2.131568
8 -0.207709
9 -1.208115

### Langkah 7 & 8 - Hasil setelah Pre Processing

Mengecek tampilan 5 baris pertama keseluruhan DataFrame setelah dilakukan perubahan pada kolom `Sex`, `Cabin`, dan `Age`.

In [7]:
# --- 5. Cek hasil akhir ---
print("=== Hasil Preprocessing (5 baris pertama) ===")
#print(df[['Sex', 'Cabin', 'Age']].head(5))
df.head()

=== Hasil Preprocessing (5 baris pertama) ===

   PassengerId  Survived  Pclass  ...     Fare  Cabin  Embarked
0            1         0       3  ...   7.2500      D         S
1            2         1       1  ...  71.2833      C         C
2            3         1       3  ...   7.9250      D         S
3            4         1       1  ...  53.1000      C         S
4            5         0       3  ...   8.0500      D         S

[5 rows x 12 columns]

### Langkah 9 - Seleksi Fitur

Memilih 5 variabel penting yang relevan terhadap keselamatan penumpang, yaitu `Survived`, `Pclass`, `Age`, `Sex`, dan `Cabin`.

In [8]:
df = df[['Survived', 'Pclass', 'Age', 'Sex', 'Cabin']]
df.head()

   Survived  Pclass       Age  Sex Cabin
0         0       3 -0.592481    1     D
1         1       1  0.638789    0     C
2         1       3 -0.284663    0     D
3         1       1  0.407926    0     C
4         0       3  0.407926    1     D

Dari hasil akhir seleksi fitur di atas, dimensi data tereduksi dari 12 kolom menjadi 5 kolom utama (`Survived`, `Pclass`, `Age`, `Sex`, dan `Cabin`) yang sudah melewati tahap pra pengolahan: kolom `Sex` bernilai `1` atau `0`, kolom `Cabin` tergeneralisasi menjadi huruf dek (`D`, `C`, `E`, dll.), dan kolom `Age` sudah berada dalam skala standar (z-score).